import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import Head from "next/head";
import Script from "next/script";
import Navbar from "./components/Navbar";
import Topbar from "./components/Topbar";
import Footer from "./components/Footer";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Google Web Fonts */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin=""
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&family=Saira:wght@500;600;700&display=swap"
          rel="stylesheet"
        />
        {/* Icon Font Stylesheet */}
        <link
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css"
          rel="stylesheet"
        />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css"
          rel="stylesheet"
        />

        <link rel="stylesheet" href="lib/animate/animate.min.css" />
        <link
          rel="stylesheet"
          href="lib/owlcarousel/assets/owl.carousel.min.css"
        />
        <link rel="stylesheet" href="css/bootstrap.min.css" />
        <link rel="stylesheet" href="css/style.css" />
      </head>
      <body className={inter.className}>
        <Topbar />
        <Navbar />
        {children}
        <Footer />
        <Script
          src="lib/easing/easing.min.js"
          strategy="beforeInteractive"
        ></Script>
        <Script
          src="lib/waypoints/waypoints.min.js"
          strategy="afterInteractive"
        ></Script>
        <Script
          src="lib/owlcarousel/owl.carousel.min.js"
          strategy="afterInteractive"
        ></Script>
        <Script src="js/main.js" strategy="afterInteractive"></Script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
        <script src="lib/wow/wow.min.js"></script>
      </body>
    </html>
  );
}
